# Generated by Django 5.2.7 on 2025-11-07 13:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_fk_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='SweetReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(db_column='rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, db_column='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('sweet', models.ForeignKey(db_column='sweet_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.sweet')),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='sweet_reviews', to='api.lineuser')),
            ],
            options={
                'db_table': 'sweet_review_tab',
                'ordering': ['-created_at'],
            },
        ),
    ]
